#!/bin/sh
# tomld service script

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
DAEMON=/usr/local/sbin/tomld
LOGFILE=/var/log/tomld.log
KILLALL=/usr/bin/killall

case $1 in
	start)
		echo "Starting tomld"
		test -x $DAEMON && $DAEMON >> $LOGFILE &
		;;
	stop)
		echo "Stopping tomld"
		test -x $KILLALL && $KILLALL -w tomld
		;;
	restart)
		$0 stop
		$0 start
		;;
	learn)
		test -x $DAEMON && $DAEMON --learn
		;;
	*)
		echo "Usage: $0 {start|stop|restart|learn}"
		;;
esac
