#!/bin/sh
# tomld service script

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
DAEMON=/usr/local/sbin/tomld
DAEMON2=/usr/sbin/tomld
LOGFILE=/var/log/tomld.log
KILLALL=/usr/bin/killall

test -x $DAEMON || DAEMON=$DAEMON2

case $1 in
	start)
		echo "Starting tomld"
		$DAEMON >> $LOGFILE &
		;;
	stop)
		echo "Stopping tomld"
		$KILLALL -w tomld
		;;
	restart)
		$0 stop
		$0 start
		;;
	learn)
		$DAEMON --learn
		;;
	*)
		echo "Usage: $0 {start|stop|restart|learn}"
		;;
esac
